# AUTO GENERATED BY FIREQOS-AUTOSPEED SCRIPT. DO NOT EDIT DIRECTLY!
#
# Edit my template at %TEMPLATE_PATH%

# Internet link is device usb0
DEVICE="usb0"

# Recommend setting overall rate limits to 85% of downlink and 95% of uplink
INPUT_SPEED="%DOWN_LIMIT%"
OUTPUT_SPEED="%UP_LIMIT%"

declare -A commits
commits=(
  [interactive]="20%"
  [realtime]="300kbit"
  [streaming]="10%"
  [vpn]="15%"
  [surfing]="40%"
  [synacks]="1%"
  [filesync]="1%"
  [default]="1%"
  [torrents]="1%"
)

interface $DEVICE "world-in" input rate $INPUT_SPEED qdisc fq_codel balanced
  # class workmac commit "300kbit"
  #   match4 dst 192.168.3.105

  class interactive commit "${commits[interactive]}"
    match udp port 53 # DNS
    match tcp port 22 # SSH
    match udp ports 60000:61000 # MoSH shell
    match icmp # Ping
    match tcp port 8448 # Matrix.org chat
    match tcp port 5938 # TeamViewer remote desktop
    match tcp port 5222,5228 # XMPP

  class realtime commit "${commits[realtime]}"
    match udp sports 19302:19309 # Google Hangouts UDP
    match tcp sports 19305:19309 # Google Hangouts TCP
    match tcp port 8801,8802 # Zoom conference TCP
    match udp ports 8801:8810 # Zoom conference UDP

  class streaming commit "${commits[streaming]}"
    match dscp CS1
    match dscp CS4
    match tcp port 4070 # Spotify

  class vpn commit "${commits[vpn]}"
    match port 1194 # OpenVPN
    match port 655  # Tinc Mesh VPN

  class surfing commit "${commits[surfing]}"
    match tcp sports 0:1023

  class filesync commit "${commits[filesync]}"
    match udp port 21027 # Syncthing UDP
    match tcp port 22000 # Syncthing TCP

  class synacks commit "${commits[synacks]}" # TCP handshakes
    match tcp syn
    match tcp ack

  class default commit "${commits[default]}"

  class torrents commit "${commits[torrents]}"
    match dports 6881:6999 # Official torrent port range
    match dport 51414 prio 1 # Custom fixed torrent client port

interface $DEVICE "world-out" output rate $OUTPUT_SPEED qdisc fq_codel balanced
  class interactive commit "${commits[interactive]}"
    match udp port 53 # DNS
    match tcp port 22 # SSH
    match udp ports 60000:61000 # MoSH shell
    match icmp # Ping
    match tcp port 8448 # Matrix.org chat
    match tcp dport 5938 # TeamViewer remote desktop
    match tcp port 5222,5228 # XMPP

  class realtime commit "${commits[realtime]}"
    match udp dports 19302:19309 # Google Hangouts UDP
    match tcp dports 19305:19309 # Google Hangouts TCP
    match tcp port 8801,8802 # Zoom conference TCP
    match udp ports 8801:8810 # Zoom conference UDP

  class streaming commit "${commits[streaming]}"
    match dscp CS1
    match dscp CS4
    match tcp port 4070 # Spotify

  class vpn commit "${commits[vpn]}"
    match port 1194 # OpenVPN
    match port 655  # Tinc Mesh VPN

  class surfing commit "${commits[surfing]}"
    match tcp dports 0:1023

  class filesync commit "${commits[filesync]}"
    match udp port 21027 # Syncthing UDP
    match tcp port 22000 # Syncthing TCP

  class synacks commit "${commits[synacks]}" # TCP handshakes
    match tcp syn
    match tcp ack

  class default commit "${commits[default]}"

  class torrents commit "${commits[torrents]}"
    match sports 6881:6999 # Official torrent port range
    match sport 51414 prio 1 # Custom fixed torrent client port

# vim: set ft=sh ts=2 sw=2 :
